channels:
  - currentCSV: ibm-healthcheck-operator.v3.8.0
    name: beta
  - currentCSV: ibm-healthcheck-operator.v3.8.2
    name: dev
  - currentCSV: ibm-healthcheck-operator.v3.7.2
    name: stable-v1
defaultChannel: stable-v1
packageName: ibm-healthcheck-operator-app
